#!/usr/bin/env python3
"""Regenerates reference-layer6.json from the gaborgandalf reference implementation.

The C++ EventMerger is a port of gaborgandalf's "layer 6" event merge. This
script runs the *original* Python functions - imported unmodified from
`segments.py` - over a fixed synthetic input and records what they produce, so
the port can be checked against them without needing Python at test time.

Only stages A to C are exercised. `compute_event_merge_index_to_file`, which
cuts and writes audio, is out of the port's scope.

Running it
----------
The reference needs a Python environment the current machine does not have by
default, for two reasons:

  * `scipy.signal.ricker` was deprecated in SciPy 1.12 and removed in 1.15.
  * A global PYTHONPATH pointing at Python 3.9's site-packages shadows every
    other interpreter's numpy, so it must be unset.

    python3.11 -m venv /tmp/refvenv
    env -u PYTHONPATH /tmp/refvenv/bin/pip install "numpy<2" "scipy<1.15"
    env -u PYTHONPATH /tmp/refvenv/bin/python generate-reference.py \
        --gaborgandalf ~/dev/gaborgandalf

Neither the build nor the test suite runs this - the committed JSON is the
contract. Regenerate only when the reference implementation itself changes.
"""

import argparse
import json
import os
import sys
import types


def load_reference(gaborgandalf_path):
    """Imports the reference merge functions from an unmodified segments.py.

    segments.py imports librosa and soundfile at module scope for the
    file-writing stage we do not use, and neither is needed by stages A to C,
    so they are stubbed rather than installed.
    """
    sys.modules.setdefault("librosa", types.ModuleType("librosa"))
    sys.modules.setdefault("soundfile", types.ModuleType("soundfile"))
    sys.path.insert(0, gaborgandalf_path)

    from gaborgandalf.segments import (  # noqa: E402
        compute_event_mean_intervals,
        compute_event_merge_heuristics,
        compute_event_merge_mexhat,
    )

    return (
        compute_event_mean_intervals,
        compute_event_merge_mexhat,
        compute_event_merge_heuristics,
    )


# The analysis grid the reference works on: librosa's default hop at its
# analysis rate, giving ~43.07 frames per second.
HOP_SIZE = 512
GRID_RATE = 22050.0
FRAMES_PER_SECOND = GRID_RATE / HOP_SIZE

# Roughly one minute of material.
NUM_FRAMES = 2583

# The reference's own defaults, mirrored by EventMerger::Parameters.
NUM_SEGMENTS = 20
MAX_KERNEL_POINTS = 250
KERNEL_WIDTH_DIVISOR = 10.0
MIN_SEGMENT_FRAMES = 43


def build_streams():
    """The synthetic input, shaped like what the real pipeline produces.

    Three segmentation estimates of differing granularity, and beat grids at
    three tempi plus their decimated variants - the same nine streams
    autoedit.py feeds the merge.
    """
    import numpy as np

    rng = np.random.default_rng(20260801)

    # An irregular structural segmentation, as SBic produces.
    sbic = np.unique(np.sort(rng.choice(np.arange(1, NUM_FRAMES), size=14, replace=False)))
    sbic = np.concatenate(([0], sbic))

    # Two clustering segmentations at different granularities.
    clust_1 = np.linspace(0, NUM_FRAMES - 1, 20, dtype=int)
    clust_2 = np.linspace(0, NUM_FRAMES - 1, 25, dtype=int)

    segs = [sbic, clust_1, clust_2]

    beats = []
    for bpm in (60, 90, 120):
        step = FRAMES_PER_SECOND * 60.0 / bpm
        grid = np.arange(0, NUM_FRAMES, step).astype(int)
        beats.append(grid)

    # The reference also feeds every 16th beat of each grid.
    beats.extend([grid[::16] for grid in beats[:3]])

    return segs, beats


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--gaborgandalf",
        default=os.path.expanduser("~/dev/gaborgandalf"),
        help="Path to a gaborgandalf checkout [~/dev/gaborgandalf]",
    )
    parser.add_argument(
        "--output",
        default=os.path.join(os.path.dirname(os.path.abspath(__file__)), "reference-layer6.json"),
        help="Where to write the fixture",
    )
    args = parser.parse_args()

    mean_intervals, mexhat, heuristics = load_reference(args.gaborgandalf)

    import numpy as np
    import scipy

    segs, beats = build_streams()

    kwargs = {"numframes": NUM_FRAMES, "beats": beats, "segs": segs}

    kwargs.update(mean_intervals(**kwargs))
    kwargs["numsegs"] = NUM_SEGMENTS
    kwargs.update(mexhat(**kwargs))
    result = heuristics(**kwargs)

    fixture = {
        "_comment": (
            "Generated by generate-reference.py from gaborgandalf's segments.py. "
            "Do not edit by hand - see that script's docstring to regenerate."
        ),
        "reference": {
            "source": "gaborgandalf/segments.py",
            "functions": [
                "compute_event_mean_intervals",
                "compute_event_merge_mexhat",
                "compute_event_merge_heuristics",
            ],
            "numpy": np.__version__,
            "scipy": scipy.__version__,
        },
        "grid": {"hopSize": HOP_SIZE, "gridRate": GRID_RATE},
        "params": {
            "numSegments": NUM_SEGMENTS,
            "maxKernelPoints": MAX_KERNEL_POINTS,
            "kernelWidthDivisor": KERNEL_WIDTH_DIVISOR,
            "minSegmentFrames": MIN_SEGMENT_FRAMES,
        },
        "numFrames": NUM_FRAMES,
        "segmentationStreams": [[int(f) for f in stream] for stream in segs],
        "beatStreams": [[int(f) for f in stream] for stream in beats],
        "expectedIntervals": [float(v) for v in kwargs["intervals"]],
        "expectedBoundaryFrames": [int(f) for f in result["ind_"]],
    }

    with open(args.output, "w") as handle:
        json.dump(fixture, handle, indent=2)
        handle.write("\n")

    print(f"wrote {args.output}")
    print(f"  numpy {np.__version__}, scipy {scipy.__version__}")
    print(f"  {len(segs)} segmentation + {len(beats)} beat streams over {NUM_FRAMES} frames")
    print(f"  {len(fixture['expectedBoundaryFrames'])} boundaries: {fixture['expectedBoundaryFrames']}")


if __name__ == "__main__":
    main()
