### Commented entries have reasonable defaults.
### Uncomment to edit them.
# Source: <source package name; defaults to package name>
Section: misc
Priority: optional
Homepage: https://audionaut.app/
Standards-Version: 3.9.2

Package: audionaut
Version: 1.1.2
Maintainer: Klaus Voltmer <vltmrkls@gmail.com>
# Pre-Depends: <comma-separated list of packages>
# Depends: <comma-separated list of packages>
Depends: libc6, libasound2-dev
# Recommends: <comma-separated list of packages>
# Suggests: <comma-separated list of packages>
# Provides: <comma-separated list of packages>
# Replaces: <comma-separated list of packages>
# Architecture: all
Architecture: amd64
# Multi-Arch: <one of: foreign|same|allowed>
# Copyright: <copyright file; defaults to GPL2>
# Changelog: <changelog file; defaults to a generic changelog>
# Readme: <README.Debian file; defaults to a generic one>
Copyright: ../../../LICENSE.md
# Extra-Files: <comma-separated list of additional files for the doc directory>
# Links: <pair of space-separated paths; First is path symlink points at, second is filename of link>
#Files: <pair of space-separated paths; First is file to include, second is destination>
Files: ./audionaut /usr/bin
#  <more pairs, if there's more than one file to include. Notice the starting space>
Description: Audio editing and audio recording 
    Audionaut — A lightweight desktop application for effortless audio editing and audio recording.
